name: 'Example'
description: 'example'
runs:
  using: 'composite'
  steps:
    - run: |
        echo -n "CI_JOB_JWT_V2=" >> $GITHUB_ENV
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
      shell: bash
