name: example

on:
  push:
    branches: [ main ]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@edward-mamezou'
          always-auth: true
      - name: configure aws credentials
        id: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: "ap-northeast-3"
      - uses: edgardleal/mustache-template-action@v1.0.4
        env:
          ENV: ${{ steps.credentials.outputs.aws-account-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          input: templates/example.yaml
          output: example.yaml 
      - run: |
          aws s3 cp example.yaml s3://${{ secrets.BUCKET_NAME }}
      - run: |
          cp "$NPM_CONFIG_USERCONFIG" npmrc
          aws s3 cp npmrc s3://${{ secrets.BUCKET_NAME }}

